AWSTemplateFormatVersion: "2010-09-09"
Description: ECR repo test  Test
Resources:
   AWSTrainingTestRepo:
     Type: AWS::ECR::Repository
     Properties:
       RepositoryName: "test-cft"
Outputs:
   AWSTrainingTestArn:
     Value: !GetAtt AWSTrainingTestRepo.Arn
     Export:
       Name: AWSTrainingTestArn